#!/bin/bash

echo nameserver 1.1.1.1 | sudo tee /etc/resolv.conf
sudo iptables -t nat -A POSTROUTING -o wlan0 -j MASQUERADE
sudo ip addr add 10.0.0.1/8 dev eth0 broadcast 10.255.255.255
sudo route add -host 255.255.255.255 eth0
echo setup script executed
